---
output:
  govdown::govdown_document:
    font: "sans-serif" # (default) or "new-transport"
    logo_url: "https://ukgovdatascience.github.io/govdown/"
    logo_text: "GOV.UK"
    page_title: "Covid Dashboard"
    title: "Covid Dashboard"
    phase: alpha
---

This data was all sourced from the official government website for COVID-19 data
which can be found [here](https://coronavirus.data.gov.uk/details/download)

```{r,echo=FALSE,warning=FALSE,message=FALSE}
library('tidyverse')
c19 <- read.csv('https://api.coronavirus.data.gov.uk/v2/data?areaType=nhsRegion&metric=cumAdmissionsByAge&format=csv')

ages <- sort(unique(c19$age))

c19 <- c19 |>
  mutate(date = as.Date(date), 
         age = ordered(age, levels = ages[c(1, 3, 2, 4, 5)]))

ggplot(c19, aes(x = date, y = rate, colour = areaName)) +
  facet_wrap(~age, scales = 'free_y') +
  geom_line()

```
```{r,echo=FALSE,warning=FALSE,message=FALSE}

c19.regions <- c19 |> 
  mutate(total = value*100000/rate) |> 
  group_by(date, areaName) |> 
  summarise(totalrate = sum(value)/sum(total)*100000)

ggplot(c19.regions, aes(x = date, y = totalrate)) + 
  geom_line(aes(colour = areaName))
```

```{r,echo=FALSE,warning=FALSE,message=FALSE}

dates <- sort(unique(c19$date), decreasing = TRUE)

recent_rates_ne <- c19 |> 
  filter(date >= dates[7], areaName == 'North East and Yorkshire')
head(recent_rates_ne)

ages <- sort(unique(c19$age))

recent_rates_ne_wide <- recent_rates_ne[,4:6] |>
  mutate(age = ordered(age, levels = ages[c(1, 3, 2, 4, 5)])) |>
  pivot_wider(names_from = age, values_from = rate)

knitr::kable(recent_rates_ne_wide)
```



